### ISSUE TITLE
Error in 5.2.2 Highlight clades with geom_hilight()

### ISSUE THREAD

**Issue by GaryNapier** [YuLab-SMU/treedata-book#18]
The "Using external data" section has code to highlight clades and make a legend (figures 5.4 E and F). 

However this code does not work:
```
## using external data
d <- data.frame(node=c(17, 21), type=c("A", "B"))
ggtree(tree) + geom_hilight(data=d, aes(node=node, fill=type))
```
I get an error saying:
```
Error in (function (node, mapping = NULL, fill = "steelblue", alpha = 0.5,  : 
  unused argument (data = list(c(17, 21), 1:2))
```

`geom_hilight()` does not take the argument `'data'`. 

When I also run this code:
```
x <- read.nhx(system.file("extdata/NHX/ADH.nhx", package="treeio"))
ggtree(x) + geom_hilight(mapping=aes(subset = node %in% c(10, 12), fill = S)) +
  scale_fill_manual(values=c("steelblue", "darkgreen"))
```
I get a similar error:

```
Error in structure(list(node = node, fill = fill, alpha = alpha, extend = extend,  : 
  argument "node" is missing, with no default
```

**Comment by GuangchuangYu** [comment]
make sure you are using the same version that we used to run these examples. 

The versions were listed right below the `Introduction` in <http://yulab-smu.top/treedata-book/>.

Apparently, you need to upgrade ggtree.

**Comment by GaryNapier** [comment]
Hi Guangchuang,

I'm having trouble installing the latest ggtree package.

I uninstalled the package, then I went to the Bioconductor page -
https://bioconductor.org/packages/release/bioc/html/ggtree.html

I re-installed ggtree using the instructions there, but the version is
still 2.0.4, not 2.3.4.992 as it says on the Introduction page -
http://yulab-smu.top/treedata-book/

Any help would be greatly appreciated.

Thanks,

Gary

**Comment by xiangpin** [comment]
You can install the developed version by [Bioconductor](https://www.bioconductor.org/packages/devel/bioc/html/ggtree.html).
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# The following initializes usage of Bioc devel
BiocManager::install(version='devel')

BiocManager::install("ggtree")
```
Or you can install the latest ggtree by `github`
```
if (!requireNamespace("remotes", quietly = TRUE))
    install.packages("remotes")

remotes::install_github("YuLab-SMU/ggtree")
```

**Comment by GaryNapier** [comment]
Ok, thanks Shuangbin, it seems to be working now! I think it would be a
good idea to make this much clearer in the documentation.

Many thanks,

Gary
