### ISSUE TITLE
Error in 5.2.2 Highlight clades with geom_hilight() - still does not work

### ISSUE THREAD

**Issue by GaryNapier** [YuLab-SMU/treedata-book#19]
Hi Guangchuang, 

I have updated everything to the latest versions, and sorry the code is still not working:

ggtree version 2.2.4

> R.version
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again 

```
## using external data
d <- data.frame(node=c(17, 21), type=c("A", "B"))
ggtree(tree) + geom_hilight(data=d, aes(node=node, fill=type))

Error in (function (node, mapping = NULL, fill = "steelblue", alpha = 0.5,  : 
  unused argument (data = list(c(17, 21), c("A", "B")))
```

```
## using data stored in tree object
x <- read.nhx(system.file("extdata/NHX/ADH.nhx", package="treeio"))
ggtree(x) + geom_hilight(mapping=aes(subset = node %in% c(10, 12), fill = S)) +
  scale_fill_manual(values=c("steelblue", "darkgreen"))

Error in structure(list(node = node, fill = fill, alpha = alpha, extend = extend,  : 
  argument "node" is missing, with no default
```

Could you please shed any light on why my code is not working?

Many thanks!

**Comment by GuangchuangYu** [comment]
install the github version will solve your issue.
