### ISSUE TITLE
Transfer to ropensci-books org?

### ISSUE THREAD

**Issue by maelle** [YuLab-SMU/treedata-book#2]
Hi @GuangchuangYu, I see that this is a book concerning an rOpenSci package and was therefore wondering whether you'd like to transfer it to the ropensci-books organization. 

E.g. drake manual https://github.com/ropensci-books/drake with the rendered book in the gh-pages branch

URL https://books.ropensci.org/drake/

The advantages are getting such a pretty URL and being listed in https://books.ropensci.org/ You'd retain admin rights on your book repo.

There's absolutely no obligation!

cc @jeroen (who set up the ropensci-books org)

**Comment by GuangchuangYu** [comment]
that's a good idea. However, the link was listed in a recent published paper, <https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msz240/5601621>. I think it would be better to keep the url unchanged.

**Comment by maelle** [comment]
Right, you could have a redirect but I understand if you close this issue!
