### ISSUE TITLE
error when plotting tree with data, please help

### ISSUE THREAD

**Issue by cmavian** [YuLab-SMU/treedata-book#24]
Hi, 

I was trying to plot an ML tree with data based on the example here:https://yulab-smu.top/treedata-book/chapter7.html#ggtree_object , chapter: 7.1 mapping data to the tree strucutre

And to start, I was following the script that is given in the webpage but I’m getting errors, it seems not to recognize my metadata. 

I am attaching the tree and the metadata and my code . 

Can you help me?

Thank you, 

Carla 

###### tree.nwk ######
(Miami_VP01-BL-D-4Seq-1_Freq_31.4546304957905:0.0391764546,((((((((Miami_VP01-BL-D-4Seq-2_Freq_7.97474275023386:0.0180673245,(Miami_VP01-BL-D-4Seq-4_Freq_7.20299345182413:0.0288746301,Miami_VP01-BL-D-4Seq-7_Freq_3.99906454630496:0.0093703420)100:0.0186559944)98:0.0106905559,Miami_VP01-BL-D-4Seq-5_Freq_5.00467726847521:0.0204139776)92:0.0102525246,(Miami_VP01-BL-D-4Seq-3_Freq_14.9672591206735:0.0233094297,Miami_VP01-BL-D-4Seq-6_Freq_4.09260991580917:0.0116586417)94:0.0125728907)71:0.0019297308,(((Miami_VP01-R-3Seq-1_Freq_40.9963116858864:0.0080173189,(Miami_VP01-R-3Seq-4_Freq_10.6494234091227:0.0061503988,Miami_VP01-R-3Seq-5_Freq_4.99556468555955:0.0144382491)80:0.0018165748)52:0.0000010000,((Miami_VP01-R-3Seq-2_Freq_8.14230356225781:0.0079434585,Miami_VP01-R-3Seq-3_Freq_21.1261029926701:0.0059381860)42:0.0000010000,Miami_VP01-R-3Seq-6_Freq_4.38862692002428:0.0039596553)31:0.0000010000)50:0.0000010000,Miami_VP01-R-3Seq-7_Freq_2.59582613567393:0.0182658096)74:0.0022617194)88:0.0076715780,Miami_VP01-R-3Seq-8_Freq_3.4035202390401:0.0000010000)81:0.0019624401,Miami_VP01-R-3Seq-9_Freq_3.69298286568:0.0039527218)96:0.0169191950,(((((((Miami_VP01-BL-R-1Seq-1_Freq_24.7746243739566:0.0085585132,Miami_VP01-BL-R-1Seq-2_Freq_6.91151919866444:0.0042164778)28:0.0000010000,Miami_VP01-BL-R-1Seq-6_Freq_16.974958263773:0.0020997551)6:0.0000010000,(Miami_VP01-BL-R-1Seq-4_Freq_3.87312186978297:0.0000010000,Miami_VP01-BL-R-1Seq-5_Freq_5.66944908180301:0.0000010000)65:0.0000010000)5:0.0000010000,(Miami_VP01-BL-R-1Seq-7_Freq_27.7529215358932:0.0042320651,Miami_VP01-BL-R-1Seq-8_Freq_2.43739565943239:0.0020956728)27:0.0000010000)28:0.0000010000,Miami_VP01-BL-R-1Seq-3_Freq_7.18530884808013:0.0063358778)82:0.0018083868,Miami_VP01-BL-R-1Seq-9_Freq_4.41402337228715:0.0045438562)100:0.0616779797,(((((Miami_VP01-R-2Seq-1_Freq_29.8493267257346:0.0282875513,Miami_VP01-R-2Seq-9_Freq_7.49361766030936:0.0044904112)81:0.0018040480,((Miami_VP01-R-2Seq-2_Freq_9.83130600190219:0.0019812472,Miami_VP01-R-2Seq-6_Freq_8.52980928067277:0.0084323992)90:0.0063325096,Miami_VP01-R-2Seq-4_Freq_5.57140711818591:0.0061799056)44:0.0000010000)61:0.0000010000,(Miami_VP01-R-2Seq-3_Freq_8.99033888972318:0.0125674004,Miami_VP01-R-2Seq-5_Freq_21.3445462281624:0.0147813306)67:0.0019949554)89:0.0084176437,Miami_VP01-R-2Seq-7_Freq_5.03579115983381:0.0040679009)84:0.0104814500,Miami_VP01-R-2Seq-8_Freq_3.34885117885568:0.0134109984)81:0.0051375462)95:0.0142570091)93:0.0110711000,Miami_VP01-BL-D-4Seq-8_Freq_13.4471468662301:0.0042512688)57:0.0012129753,Miami_VP01-BL-D-4Seq-9_Freq_11.8334892422825:0.0093601630);

###### metadata.csv #######

name,condition,frequency
Miami_VP01-BL-D-4Seq-1_Freq:31.4546304957905,Baseline DNA,31.5
Miami_VP01-BL-D-4Seq-2_Freq:7.97474275023386,Baseline DNA,8
Miami_VP01-BL-D-4Seq-3_Freq:14.9672591206735,Baseline DNA,15
Miami_VP01-BL-D-4Seq-4_Freq:7.20299345182413,Baseline DNA,7.2
Miami_VP01-BL-D-4Seq-5_Freq:5.00467726847521,Baseline DNA,5
Miami_VP01-BL-D-4Seq-6_Freq:4.09260991580917,Baseline DNA,4.1
Miami_VP01-BL-D-4Seq-7_Freq:3.99906454630496,Baseline DNA,4
Miami_VP01-BL-D-4Seq-8_Freq:13.4471468662301,Baseline DNA,13.4
Miami_VP01-BL-D-4Seq-9_Freq:11.8334892422825,Baseline DNA,11.8
Miami_VP01-BL-R-1Seq-1_Freq:24.7746243739566,Baseline RNA,24.8
Miami_VP01-BL-R-1Seq-2_Freq:6.91151919866444,Baseline RNA,6.9
Miami_VP01-BL-R-1Seq-3_Freq:7.18530884808013,Baseline RNA,7.2
Miami_VP01-BL-R-1Seq-4_Freq:3.87312186978297,Baseline RNA,3.9
Miami_VP01-BL-R-1Seq-5_Freq:5.66944908180301,Baseline RNA,5.7
Miami_VP01-BL-R-1Seq-6_Freq:16.974958263773,Baseline RNA,17
Miami_VP01-BL-R-1Seq-7_Freq:27.7529215358932,Baseline RNA,27.8
Miami_VP01-BL-R-1Seq-8_Freq:2.43739565943239,Baseline RNA,2.4
Miami_VP01-BL-R-1Seq-9_Freq:4.41402337228715,Baseline RNA,4.4
Miami_VP01-R-2Seq-1_Freq:29.8493267257346,After culture no co-culture RNA,29.8
Miami_VP01-R-2Seq-2_Freq:9.83130600190219,After culture no co-culture RNA,9.8
Miami_VP01-R-2Seq-3_Freq:8.99033888972318,After culture no co-culture RNA,9
Miami_VP01-R-2Seq-4_Freq:5.57140711818591,After culture no co-culture RNA,5.6
Miami_VP01-R-2Seq-5_Freq:21.3445462281624,After culture no co-culture RNA,21.3
Miami_VP01-R-2Seq-6_Freq:8.52980928067277,After culture no co-culture RNA,8.5
Miami_VP01-R-2Seq-7_Freq:5.03579115983381,After culture no co-culture RNA,5
Miami_VP01-R-2Seq-8_Freq:3.34885117885568,After culture no co-culture RNA,3.3
Miami_VP01-R-2Seq-9_Freq:7.49361766030936,After culture no co-culture RNA,7.5
Miami_VP01-R-3Seq-1_Freq:40.9963116858864,After culture co-culture RNA,41
Miami_VP01-R-3Seq-2_Freq:8.14230356225781,After culture co-culture RNA,8.1
Miami_VP01-R-3Seq-3_Freq:21.1261029926701,After culture co-culture RNA,21.1
Miami_VP01-R-3Seq-4_Freq:10.6494234091227,After culture co-culture RNA,10.6
Miami_VP01-R-3Seq-5_Freq:4.99556468555955,After culture co-culture RNA,5
Miami_VP01-R-3Seq-6_Freq:4.38862692002428,After culture co-culture RNA,4.4
Miami_VP01-R-3Seq-7_Freq:2.59582613567393,After culture co-culture RNA,2.6
Miami_VP01-R-3Seq-8_Freq:3.4035202390401,After culture co-culture RNA,3.4
Miami_VP01-R-3Seq-9_Freq:3.69298286568,After culture co-culture RNA,3.7

#### CODE ####

library(ggtree)
x <- read.tree("tree.nwk")
info <- read.csv("metadata.csv")
p <- ggtree(x) %<+% info + xlim(-.1, 4)
plot(p)
p2 <- p + 
  geom_tippoint(aes(shape = condition, color = condition, size = frequency) +
  theme(legend.position = "right")) #+ scale_size_continuous(range = c(3, 10)))

plot(p2)

**Comment by xiangpin** [comment]
because the `name` column of `metadata` is not consistent with the `tip.label` of your tree. You should modify the `name` column of `metadata` firstly.

```
library(ggtree)
x <- read.tree("tree.nwk")
info <- read.csv("metadata.csv")
##### modified the name column
info$name <- gsub(":", "_", info$name)
p <- ggtree(x) %<+% info
p2 <- p +
geom_tippoint(aes(shape = condition, color = condition, size = frequency)) 
p2
```
![捕获](https://user-images.githubusercontent.com/17870644/113391305-ed0fad00-93c5-11eb-8449-2b195b0a7cc6.PNG)
