### ISSUE TITLE
Change spelling of `geom_hilight`

### ISSUE THREAD

**Issue by swuyts** [YuLab-SMU/treedata-book#4]
Hi @GuangchuangYu,

I was following along in your treedata-book to refresh my `ggtree`-skills. Thank you for this very valuable resource.

During this read, I stumbled on the layer function `geom_hilight` (Chapter 4), which is used to highlight a clade. However, I believe that `geom_hilight` is misspelled and should be changed to `geom_highlight`. See for example this [recourse](https://en.wiktionary.org/wiki/hilight). 

Thank you for considering this change and the development of the packages.

Regards,
Sander

**Comment by GuangchuangYu** [comment]
`geom_hilight` is shorter, similar to `ls` for `list` in shell.

Now I export `geom_highlight` as an alias of `geom_hilight` and you can use both of them, <https://github.com/YuLab-SMU/ggtree/commit/d903c8a1f0ef7460d75316558a3b218b3b6d723a>.
