### ISSUE TITLE
ylim2() does not appear in the ggtree package in R.

### ISSUE THREAD

**Issue by MeloOspino** [YuLab-SMU/treedata-book#5]
Hi Professor Yu.

I am always being a fan of ggtree, and try to used it whenever I can. 
I was trying to use the ylim2() function to plot my tree with other plot next to it. However, ylim2 doesn't appear in the ggtree package. I am using the ggtree version 2.0.1.

Maybe I am looking in the wrong direction. Thank you for the help and this great package!.

Melody

EDIT: I found the newest version. I was using the old one. As I though, I was looking in the wrong direction. Thank you for your constantly effort in this amazing package!

**Comment by geekyi** [comment]
Looks like I'm having a similar issue with an outdated ggtree #6.
How did you fix this? 
`BiocManager::install("ggtree")` appears to give me version 2.0.1 too!

**Comment by MeloOspino** [comment]
Hi @geekyi 
I install thel the latest version of this package by entering the following in R:
```
install.packages("remotes") 
remotes::install_github("YuLab-SMU/ggtree")
```

**Comment by markeletona** [comment]
Dear all,

I have downloaded the latest version of ggtree (v. 2.0.2) and realised that `ylim2()` was not present (see [manual](http://bioconductor.org/packages/release/bioc/manuals/ggtree/man/ggtree.pdf)). However, and if anybody arrives here for a similar reason than me, I have learned that it has been migrated to the [aplot](https://github.com/YuLab-SMU/aplot) package.

**Comment by GuangchuangYu** [comment]
The `xlim2` and `ylim2` previously in ggtree v=2.1.X has been removed and now available in CRAN package [aplot](https://github.com/YuLab-SMU/aplot), which provides more utilities for aligning associated subplots.
