### ISSUE TITLE
mypkg function issue

### ISSUE THREAD

**Issue by boltomli** [YuLab-SMU/treedata-book#56]
Quitting from lines 43-67 (treedata.Rmd)
Error in mypkg("Archaeopteryx", "https://sites.google.com/site/cmzmasek/home/software/archaeopteryx") :
  没有"mypkg"这个函数
Calls: render_book ... eval -> eval -> source -> withVisible -> eval -> eval

??mypkg
yulab.utils::get_fun_from_pkg
                        get_fun_from_pkg
  Aliases: get_fun_from_pkg

**Comment by GuangchuangYu** [comment]
在`yulab.utils`包中定义了。
