### ISSUE TITLE
Example files

### ISSUE THREAD

**Issue by avonm** [YuLab-SMU/treedata-book#7]
Hi,
I found your treedata-book and found it useful. 

Although, as I am new to R and what I usually find most irritating when looking at examples of different code is that the input file is never posted. My input file, for example a csv with SNP data may look different to the one you use depending on what you've used to generate the SNP data with. 

What I think would be great is to actually show what your input files that you use in your different examples look like. Even better if you would want to include the files that you've used in your examples and then a new user could try and replicate using your files first before moving onto their own files!

Great book though!

**Comment by GuangchuangYu** [comment]
example data can be found on <https://github.com/YuLab-SMU/treedata-book/tree/master/data>.

**Comment by avonm** [comment]
Yeah! Wonderful!! Sorry if I missed it, take Care
