### ISSUE TITLE
Example with ggtree of hclust object doesn't work

### ISSUE THREAD

**Issue by aushev** [YuLab-SMU/treedata-book#8]
I was trying to reproduce example from the [Chapter 9.2: ggtree for dendrograms](https://yulab-smu.github.io/treedata-book/chapter9.html#dendrogram):
```
hc <- hclust(dist(mtcars))
p <- ggtree(hc)
```
It gives an error:
```
Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S3 object with class hclust
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by GuangchuangYu** [comment]
currently it requires devel branch of ggtree which will be released at the end of this month.
